### ISSUE TITLE
Server-side validation of reCACPTHA instead of JS on Storefront in the specific case

### ISSUE THREAD

**Issue by VasylShvorak** [magento/securify#212] opened 2020-04-17 11:10 UTC
**Note**:  reCAPCTHA cannot be bypassed and Customer still requires to complete a challenge (e.g. select pictures). Issue only about error message 

### Preconditions (*)

1. Magento with security-package 1.0-develop
2. Simple product is created
3. Customer is created

### Steps to reproduce (*)

1. Configure reCAPTCHA v2 ("I am not a robot")
2. Set Enable for Customer Login=reCAPTCHA v2 ("I am not a robot")
3. Add product to cart 
4. Click Proceed to Checkout on minicart
5. Fill email of registered customer and **wrong** password
6. Do NOT check recaptcha checkbox
7. Click Login
:heavy_check_mark: Validation message "This is a required field." is shown
8.  Now **check** recaptcha checkbox
9. Click Login
:heavy_check_mark: Validation message "Invalid login or password." is shown
10. Leave recaptcha checkbox **unchecked**
11. Click Login again

### Expected result (*)

1. Validation message "This is a required field." is shown for unchecked recaptcha checkbox

### Actual result (*)

1. Validation message "reCAPTCHA verification failed" is shown for unchecked recaptcha checkbox
2. Form is submitted without checked recaptcha checkbox 
![RecapthcaCheckboxLogin](https://user-images.githubusercontent.com/26908019/79563190-f7517200-80b4-11ea-960a-25799e773c25.gif)

**Comment by engcom-Lima** [comment] 2020-06-12 11:53
**Preconditions**
Magento with security-package 1.0-develop from `magento/security-package#242V2`
**Steps to reproduce** 
1. Configure reCAPTCHA v2 ("I am not a robot")
2. Enable for Contact Us = reCAPTCHA v2 ("I am not a robot")
3. Enable for Newsletter Subscription = reCAPTCHA v2 ("I am not a robot") -> Save
4. Go to Store View 
5. Open 'Contact Us' page
6. Open any page that contains "Newsletter Subscription" field
7. Enter into 'Newsletter Subscribe' form any valid email 
8. Don`t mark ReCAPTCHA 
9. Press Enter

**Expected result** 
Error "This is a required field." is shown
**Actual result**
No error. Page scroll up
![Peek 2020-06-12 14-51](https://user-images.githubusercontent.com/60198022/84500067-7c739480-acbc-11ea-90b9-80dcb4236aaa.gif)

**Comment by nathanjosiah** [comment] 2021-02-25 18:14
Hello @VasylShvorak  and thank your for your contribution! We are closing this issue as part of our backlog triaging process because we have decided not to work on this issue internally. You are still welcome to contribute to this if you wish and we can reopen if you want to work on it.

**Closed as completed by nathanjosiah** 2021-02-25 18:14 UTC
Labels: bug, Component: Google reCAPTCHA, 2.4-develop: exclude, Severity: S3, Priority: P3, Triage: Done, Progress: done
